### ISSUE TITLE
Bug: Program Crash

### ISSUE THREAD

**Issue by giuseppemr** [schollz/find3-cli-scanner#44]
## Expected Behavior
I want the script to run forever but it crashes with the following error

## Actual Behavior

panic: runtime error: slice bounds out of range

goroutine 2561 [running]:
panic(0x4b35a0, 0x10f22030)
        /usr/local/go/src/runtime/panic.go:500 +0x33c
github.com/schollz/gatt.(*Advertisement).unmarshall(0x111e8820, 0x111e4eea, 0xb, 0x16, 0x0, 0x0)
        /home/pi/mygo/src/github.com/schollz/gatt/adv.go:98 +0xbc0
github.com/schollz/gatt.(*device).Init.func3(0x111ea750)
        /home/pi/mygo/src/github.com/schollz/gatt/device_linux.go:97 +0x74
github.com/schollz/gatt/linux.(*HCI).handleAdvertisement(0x11062280, 0x111b3bf3, 0x23, 0x23)
        /home/pi/mygo/src/github.com/schollz/gatt/linux/hci.go:262 +0x370
created by github.com/schollz/gatt/linux.(*HCI).handleLEMeta
        /home/pi/mygo/src/github.com/schollz/gatt/linux/hci.go:359 +0xc8

## Steps to Reproduce the Problem

  1. sudo ./find3-cli-scanner -i wlan1 -device MYDEV-family FAMILY -server http://localhost:8080 -scantime 2 -bluetooth -forever -passive -no-modify
  1. after some scans it crashes
  1.

## Specifications

  - Version: latest of July 2019
  - Platform: Raspberry 3+
  - Subsystem:

**Comment by giuseppemr** [comment]
Upgraded program to 3.3.4 version and the crash still happens

**Comment by schollz** [comment]
Is that the full stack trace?

**Comment by giuseppemr** [comment]
Yes. Nothing more

**Comment by ryalberti** [comment]
Hi, I'm having the same problem. Was there any update on this?

**Comment by giuseppemr** [comment]
Hello, I don't know. I haven't been using that in years sorry.
________________________________
Da: ryalberti ***@***.***>
Inviato: martedì 27 febbraio 2024 08:03
A: schollz/find3-cli-scanner ***@***.***>
Cc: giuseppemr ***@***.***>; Author ***@***.***>
Oggetto: Re: [schollz/find3-cli-scanner] Bug: Program Crash (#44)


Hi, I'm having the same problem. Was there any update on this?
